In [53]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.preprocessing import LabelEncoder , PolynomialFeatures
import warnings
from sklearn.linear_model import LinearRegression , LogisticRegression , LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error , r2_score , mean_squared_error , root_mean_squared_error
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.fillna({'age':df['age'].mean()},inplace=True)

In [4]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [6]:
df = df[['sex','age','fare','survived']]

In [12]:
le = LabelEncoder()
df['sex']=le.fit_transform(df['sex'])

In [13]:
df

,sex,age,fare,survived
0,1,22.000000,7.2500,0
1,0,38.000000,71.2833,1
2,0,26.000000,7.9250,1
3,0,35.000000,53.1000,1
4,1,35.000000,8.0500,0
...,...,...,...,...
886,1,27.000000,13.0000,0
887,0,19.000000,30.0000,1
888,0,29.699118,23.4500,0
889,1,26.000000,30.0000,1


In [15]:
x = df[['sex','age','fare']]
y= df['survived']

In [16]:
model_linear = LinearRegression()

In [39]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.25)

In [20]:
model_linear.fit(x_train,y_train)

LinearRegression()

In [21]:
y_pred = model_linear.predict(x_test)

In [23]:
y_pred

array([0.17375477, 0.16463995, 0.17526114, 0.75312435, 0.70862793,
       0.79787433, 0.68231741, 0.19625803, 0.70053489, 0.72538482,
       0.22295025, 0.14353977, 0.70988612, 0.1608736 , 0.16188102,
       0.74978502, 0.2154518 , 0.68244065, 0.17384948, 0.20794027,
       0.16989639, 0.18562565, 0.69670755, 0.17728406, 0.17259425,
       0.21964225, 0.17946854, 0.16853017, 0.22762123, 0.6807496 ,
       0.17654553, 0.69255592, 0.19779631, 0.68200619, 0.17811531,
       0.17611234, 0.20753159, 0.68231741, 0.71809629, 0.16231754,
       0.27597167, 0.16192457, 0.16255749, 0.16209066, 0.67240217,
       0.22173894, 0.17695401, 0.17329457, 0.16858025, 0.28866134,
       0.73307091, 0.78609545, 0.17974739, 0.36162797, 0.11514654,
       0.80975783, 0.16331012, 1.02842476, 0.69588629, 0.69674645,
       0.1736979 , 0.72280839, 0.71297552, 0.19037253, 0.16209066,
       0.65029115, 0.27597167, 0.16321488, 0.17816791, 0.76239112,
       0.71563518, 1.09409369, 0.20163278, 0.78729065, 0.17116

In [27]:
model_linear.score(x_test,y_test)

0.3657645071448782

In [28]:
mean_absolute_error(y_pred,y_test)


0.4666581718942791

In [29]:
np.sqrt(mean_absolute_error(y_pred,y_test))

np.float64(0.6831238334989339)

In [30]:
r2_score(y_pred,y_test)

-2.980258535509687

In [31]:
model_linear.coef_

array([-0.52022674, -0.00132983,  0.00155609])

In [32]:
model_linear.intercept_

np.float64(0.7097524788360651)

####  Polynomial 

In [33]:
Poly = PolynomialFeatures(degree=2)

In [41]:
x_train_poly = Poly.fit_transform(x_train)
x_test_poly = Poly.transform(x_test)

In [35]:
model_poly = LinearRegression()

In [36]:
model_poly.fit(x_train_poly,y_train)

LinearRegression()

In [37]:
y_pred_poly = model_poly.predict(x_test_poly)

In [42]:
model_poly.score(x_test_poly,y_test)

0.35463719138886385

####  Logistic

In [44]:
model_logistic = LogisticRegression()

In [45]:
model_logistic.fit(x_train,y_train)

LogisticRegression()

In [46]:
y_pred_logistic = model_logistic.predict(x_test)

In [47]:
model_logistic.score(x_test,y_test)

0.7847533632286996

In [49]:
y_pred_logistic[:10]

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [50]:
y_test[:10]

464    0
777    1
222    0
712    1
721    0
802    1
577    1
616    0
650    0
107    1
Name: survived, dtype: int64

In [51]:
df.corr()

,sex,age,fare,survived
sex,1.000000,0.084153,-0.182333,-0.543351
age,0.084153,1.000000,0.091566,-0.069809
fare,-0.182333,0.091566,1.000000,0.257307
survived,-0.543351,-0.069809,0.257307,1.000000
